"from fastapi import FastAPI"
"from pydantic import BaseModel"
"import uvicorn"
"import os"
""
"PORT = int(os.environ.get('PORT', 8000))"
""
"app = FastAPI()"
""
"class Request(BaseModel):"
"    text: str = 'Hello'"
""
"@app.get('/')"
"def root():"
"    return {'status': 'ok', 'service': 'DOCX Generator'}"
""
"@app.get('/health')"
"def health():"
"    return {'status': 'healthy'}"
""
"@app.post('/generate-docx')"
"def generate(data: Request):"
"    return {'message': data.text, 'filename': 'output.docx'}"
""
"if __name__ == '__main__':"
"    uvicorn.run(app, host='0.0.0.0', port=PORT)"
